### ISSUE TITLE
Trace and graph mis-match

### ISSUE THREAD

**Issue by ghost** [shivam-nagar/philo-wiki#3]
Tracing the word 'eyebrow' gives 'energy' as first node in the trace list, but 'physics' in the graph.

**Comment by shivam-nagar** [comment]
To keep the graph short and to increase hit rate I've added logic to search for 'philosophy' in 1st paragraph. 
Following was the trace for 'eyebrow' I got:

```
Eyebrow -> Human eye -> Sensory system -> Nervous system -> Eumetazoa -> Clade -> Tree of life (biology) -> Metaphor -> Figure of speech -> Literal and figurative language -> Language -> Philosophy
```

Thanks for checking by ;) :+1:

**Comment by shivam-nagar** [comment]
Give me a screenshot or reproduction route to get to the issue.. Else I'll close this :octocat:

**Comment by ghost** [comment]
I get the same trace as you now. Curious. :confused:

**Comment by shivam-nagar** [comment]
Not reproducible.. Closing issue :+1:
